/**
 * Site-wide configuration — the single source of truth for SEO.
 *
 * Only what is the same in every language lives here. Titles and descriptions
 * are copy, so they sit with the rest of it in `src/locales/<locale>.json` and
 * are read through `getSiteMeta`.
 *
 * Consumed by the metadata generator, `robots.ts`, `sitemap.ts`, and the JSON-LD
 * structured-data helper.
 */
import { getCopy, localeHref, type Locale } from "@/locales";
import { publicEnv } from "@/env";

export const siteConfig = {
  /** The brand, not the page title — this is `siteName` and the JSON-LD Organization. */
  name: "FarEdge Labs",
  /**
   * Public origin, no trailing slash. Drives canonical URLs, OG tags, the
   * sitemap, and JSON-LD. Set `NEXT_PUBLIC_SITE_URL` in production — until it
   * is, every canonical and OG URL points at localhost and no social scraper
   * can fetch the card.
   */
  url: publicEnv.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  /**
   * `undefined` on purpose, and it should stay that way until someone confirms
   * the real account. `twitter:site` is a *claim about who owns this site*, so a
   * guessed handle credits whichever stranger happens to hold the name. The
   * metadata generator omits the tags rather than invent them.
   */
  twitterHandle: undefined,
  author: "FarEdge Labs",
  /**
   * Browser theme-colour (address bar / PWA). Mirrors `--background` /
   * `--halftone-bg` in `globals.css` — the page's real ground. It cannot read
   * the token (Next needs a literal at build time), so the two move together by
   * hand.
   */
  themeColor: "#f0f3f4",
} as const;

/**
 * The per-locale half: what the tab, the search result and the share card say.
 *
 * `path` is the locale's home page, which is also its canonical URL. The default
 * locale is served from `/` rather than `/ja/` — a static export on Pages cannot
 * redirect, so the root has to *be* a locale rather than point at one.
 */
export const getSiteMeta = (locale: Locale) => {
  const { meta } = getCopy(locale);

  return {
    title: meta.title,
    description: meta.description,
    /** 1200×630, under `public/`. Regenerated by `npm run brand`. */
    ogImage: meta.ogImage,
    path: localeHref(locale),
  };
};
